### PR TITLE
added group and related tests

### PR DESCRIPTION
**Pull request by bbarker**

### CODE REVIEW

**Comment by hdgarrood** [comment]
I think this is essentially a special case of `fromFoldableWith`:

```purescript
group = fromFoldableWith (<>) <<< map (toString &&& NonEmptyArray.singleton)
```

So I’m not sure this warrants a separate function in this library, personally.

**Comment by bbarker** [comment]
I see - I guess it is time I learn profunctors. I would suggest it might still be useful to include `group` (your definition) for the following reasons:

1. A number of other core libraries provide `group`, and this seems to be the natural implementation of it for foreign-object. I suspect it is a frequently used operation, and likely would be moreso if included.
2. It provides (hopefully without much generated code) a useful example of how to use fromFoldableWith in a powerful way. Alternatively we could add it in the doc note for `fromFoldableWIth`.

**Comment by bbarker** [comment]
Here's a minor variant using a non-ambient `toStr`:

```purescript
group :: forall a f. Foldable f => Functor f =>
  (a -> String) -> f a -> FO.Object (NonEmptyArray a)
group toStr = FO.fromFoldableWith (<>) <<< map (toStr &&& NA.singleton)
```

**Comment by hdgarrood** [comment]
&&& isn’t doing anything particularly profound there, it’s just a slightly shorter way of writing `\x -> Tuple (toString x) (NonEmptyArray.singleton x)`

I’m not entirely sure that there is a natural formulation of `group` for this library actually; all of the `group` functions I’m aware of have a signature like `Collection a -> Collection (NonEmptyCollection a)`, that is, they return the same collection type as what they accept.

**Comment by bbarker** [comment]
Great points. Regarding the second, this doesn't quite match the same form, but I think it is as close as we are likely to get:

```purescript
group :: forall a f u. Foldable f => Functor f => Unfoldable1 u => Semigroup (u a) =>
  (a -> String) -> f a -> FO.Object (u a)
group toStr = FO.fromFoldableWith (<>) <<< map (toStr &&& singleton)
```

**Comment by hdgarrood** [comment]
I think the `Unfoldable1` constraint is a bit odd there, since all it's being used for is converting your type `a` to some semigroup type, and since there's nothing to guarantee that a type's `Unfoldable1` instance plays nicely with its `Semigroup` instance (if it has both). Using `Unfoldable1` also means that this function can't be used with `Set`, because `Set` can't have an `Unfoldable1` instance (because you need an `Ord` constraint to insert things). I'd therefore recommend having the conversion to the semigroup type provided explicitly as a function argument:
```purescript
group :: forall a f s.
  Foldable f =>
  Functor f =>
  Semigroup s =>
  (a -> String) ->
  (a -> s) ->
  f a ->
  Object s
```
but this is the same as
```purescript
group :: forall a f s.
  Foldable f =>
  Functor f =>
  Semigroup s =>
  (a -> Tuple String s) ->
  f a ->
  Object s
```
whose implementation would just be
```purescript
group f = fromFoldableWith (<>) <<< map f
```
which I don't think does enough beyond what `fromFoldableWith` already does to earn a spot in this library. Thanks for the PR anyway, though.

**Pull request closed without merging**
